version: "3.9"

services:
  api:
    build: ./server
    ports:
      - "5050:5050"
    env_file:
      - ./server/.env
    restart: always

  web:
    build: ./web
    ports:
      - "5173:5173"
    depends_on:
      - api
    restart: always
